services:

  laravel-docker:
    container_name: backend
    build: .
    volumes:
      - ./Backend:/var/www/html
    ports:
      - 8000:8000
  
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bitchest_db
    ports:
    - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1